# Generated by Django 4.1.7 on 2023-02-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(max_length=15)),
                ('account_name', models.CharField(max_length=32)),
                ('account_balance', models.IntegerField()),
            ],
        ),
    ]
